spring:
  servlet:
    multipart:
      max-file-size: 1000MB
      enabled: 'true'
      max-request-size: 1000MB
  datasource:
    password: pass
    username: root
    url: jdbc:mysql://localhost:3306/salt?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
  jpa:
    hibernate:
      ddl-auto: update
      hibernate:
        naming:
          implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl
          physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  show-sql: true

app:

server:
  port: 1010
  error:
  include-message: always


